### ISSUE TITLE
docker部署不成功

### ISSUE THREAD

**Issue by learningdog1** [jarvis2f/vortex#8]
你好，能否有更详细的教程。我安装原教程总是部署不成功，访问面板，出现错误：Internal Server Error
<img width="444" alt="44b47a7f9e72166f10f53301c5dbd93c" src="https://github.com/jarvis2f/vortex/assets/110441496/7fc4be3d-055c-483d-ba1d-0591e437354f">

以下是我的配置详情：
### .env

```
# Prisma
# https://www.prisma.io/docs/reference/database-reference/connection-urls#env
# postgresql://USER:PASSWORD@HOST:PORT/DATABASE
 DATABASE_URL="postgresql://vortex:123456@vortex-postgres:5432/vortex"
# If you use docker-compose, you should use the following configuration
 POSTGRES_USER="postgres"
 POSTGRES_PASSWORD="123456"
 POSTGRES_DB="vortex"



# Next Auth Providers
# Next Auth GitHub Provider
 GITHUB_CLIENT_ID="XXXXXXXX"
 GITHUB_CLIENT_SECRET="XXXXXXXXXXXXXXXXXXXX"


# Redis
REDIS_URL="redis://vortex-redis:6379"
 REDIS_USERNAME=vortex-main
REDIS_PASSWORD="123456"
REDIS_DB="0"
AGENT_REDIS_URL=redis://XXXXXXX:6379
# This should accessible by the agent node
# AGENT_REDIS_URL=

# Server
SERVER_URL="https://mydomain"
AGENT_SHELL_URL="https://raw.githubusercontent.com/jarvis2f/vortex-agent/main/scripts"
JOB_ENABLED=true

# Payment
## DePay https://depay.com
DEPAY_INTEGRATION_ID=""
DEPAY_PUBLIC_KEY=""

# Umami https://umami.is/docs
#NEXT_PUBLIC_UMAMI_URL
# script.js
#NEXT_PUBLIC_UMAMI
# website id
#NEXT_PUBLIC_UMAMI_ID
```

### docker-compose

```
version: "3.3"

services:
  vortex:
    container_name: vortex
    image: jarvis2f/vortex:latest
    env_file:
      - .env
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "18000:3000"
    depends_on:
      - vortex-postgres
      - vortex-redis

  vortex-postgres:
    container_name: vortex-postgres
    image: postgres:16.1-alpine3.19
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db:/var/lib/postgresql/data

  vortex-redis:
    container_name: vortex-redis
    image: redis:7.2.4-alpine
    restart: always
    command: [redis-server, /etc/redis/redis.conf]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "18044:6379"
```

###  redis.conf
865行：
`user vortex-main on -@all +@read +@write +@connection +@pubsub +acl +info ~* &* >123456`
1045行：
`123456`
